import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import DesktopMessage from "./DesktopMessage";

const yekanBakhLight = localFont({
  src: "./fonts/YekanBakhFaNum-Light.woff2",
  variable: "--font-yekanBakh-light",
  weight: "100 200",
});
const yekanBakhRegular = localFont({
  src: "./fonts/YekanBakhFaNum-Regular.woff2",
  variable: "--font-yekanBakh-regular",
  weight: "300 500",
});

const yekanBakhBold = localFont({
  src: "./fonts/YekanBakhFaNum-Bold.woff2",
  variable: "--font-yekanBakh-bold",
  weight: "600 700",
});
const yekanBakhBlack = localFont({
  src: "./fonts/YekanBakhFaNum-Black.woff2",
  variable: "--font-yekanBakh-black",
  weight: "800 900",
});
const lobesterFont = localFont({
  src: "./fonts/Lobster-Regular.woff2",
  variable: "--font-lobester",
  weight: "800",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${yekanBakhLight.variable} ${yekanBakhRegular.variable} ${yekanBakhBold.variable} ${yekanBakhBlack.variable} ${lobesterFont.variable} antialiased`}
      >
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 4000,
            style: {
              background: "#363636",
              color: "#fff",
            },
          }}
        />
        <DesktopMessage>{children}</DesktopMessage>
      </body>
    </html>
  );
}
